# Sample workflow for building and deploying a Nuxt site to GitHub Pages
#
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
#
name: deploy

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['develop']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup Git Client
              run: |
                  ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                  git config --global user.email "github-actions@doesnotmatter.dev"
                  git config --global user.name "GitHub Actions"

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.0.0'

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: |
                      - recursive: true
                      - args: [--global, typescript]

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: |
                      dist
                      .nuxt
                  key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
                  restore-keys: |
                      ${{ runner.os }}-nuxt-build-

            - name: Install dependencies
              run: pnpm install

            - name: Nuxt build
              run: pnpm run build

            - name: Push artifacts
              run: |
                  git clone --depth 1 --single-branch -b deploy git@github.com:thunfisch987/maguronetwork2.git deploy
                  mv deploy/.git deploy-.git
                  rm -rf deploy
                  mkdir deploy
                  mv deploy-.git deploy/.git
                  cd deploy
                  cp -RT ../.output/ .
                  git add .
                  git diff --staged --quiet || git commit -m "${{ github.event.head_commit.message }}"
                  git push
